#include <stdio.h>
#include <stdlib.h>
#include <main.h>

// when the dice is rolled it should
void put_die_dots(int number)
{
	switch(number)
	{
		case 1:
			HAL_GPIO_WritePin(BOTTOM_RIGHT_GPIO_Port, BOTTOM_RIGHT_Pin, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(BOTTOM_MIDDLE_GPIO_Port, BOTTOM_MIDDLE_Pin, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(BOTTOM_LEFT_GPIO_Port, BOTTOM_LEFT_Pin, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(DI_middle_GPIO_Port, DI_middle_Pin, GPIO_PIN_SET);
			HAL_GPIO_WritePin(TOP_RIGHT_GPIO_Port ,TOP_RIGHT_Pin, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(TOP_MIDDLE_GPIO_Port, TOP_MIDDLE_Pin, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(TOP_LEFT_GPIO_Port, TOP_LEFT_Pin, GPIO_PIN_RESET);
			break;
		case 2:
			HAL_GPIO_WritePin(BOTTOM_RIGHT_GPIO_Port, BOTTOM_RIGHT_Pin, GPIO_PIN_SET);
			HAL_GPIO_WritePin(BOTTOM_MIDDLE_GPIO_Port, BOTTOM_MIDDLE_Pin, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(BOTTOM_LEFT_GPIO_Port, BOTTOM_LEFT_Pin, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(DI_middle_GPIO_Port, DI_middle_Pin, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(TOP_RIGHT_GPIO_Port ,TOP_RIGHT_Pin, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(TOP_MIDDLE_GPIO_Port, TOP_MIDDLE_Pin, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(TOP_LEFT_GPIO_Port, TOP_LEFT_Pin, GPIO_PIN_SET);
			break;
		case 3:
			HAL_GPIO_WritePin(BOTTOM_RIGHT_GPIO_Port, BOTTOM_RIGHT_Pin, GPIO_PIN_SET);
			HAL_GPIO_WritePin(BOTTOM_MIDDLE_GPIO_Port, BOTTOM_MIDDLE_Pin, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(BOTTOM_LEFT_GPIO_Port, BOTTOM_LEFT_Pin, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(DI_middle_GPIO_Port, DI_middle_Pin, GPIO_PIN_SET);
			HAL_GPIO_WritePin(TOP_RIGHT_GPIO_Port ,TOP_RIGHT_Pin, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(TOP_MIDDLE_GPIO_Port, TOP_MIDDLE_Pin, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(TOP_LEFT_GPIO_Port, TOP_LEFT_Pin, GPIO_PIN_SET);
			break;
		case 4:
			HAL_GPIO_WritePin(BOTTOM_RIGHT_GPIO_Port, BOTTOM_RIGHT_Pin, GPIO_PIN_SET);
			HAL_GPIO_WritePin(BOTTOM_MIDDLE_GPIO_Port, BOTTOM_MIDDLE_Pin, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(BOTTOM_LEFT_GPIO_Port, BOTTOM_LEFT_Pin, GPIO_PIN_SET);
			HAL_GPIO_WritePin(DI_middle_GPIO_Port, DI_middle_Pin, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(TOP_RIGHT_GPIO_Port ,TOP_RIGHT_Pin, GPIO_PIN_SET);
			HAL_GPIO_WritePin(TOP_MIDDLE_GPIO_Port, TOP_MIDDLE_Pin, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(TOP_LEFT_GPIO_Port, TOP_LEFT_Pin, GPIO_PIN_SET);
			break;
		case 5:
			HAL_GPIO_WritePin(BOTTOM_RIGHT_GPIO_Port, BOTTOM_RIGHT_Pin, GPIO_PIN_SET);
			HAL_GPIO_WritePin(BOTTOM_MIDDLE_GPIO_Port, BOTTOM_MIDDLE_Pin, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(BOTTOM_LEFT_GPIO_Port, BOTTOM_LEFT_Pin, GPIO_PIN_SET);
			HAL_GPIO_WritePin(DI_middle_GPIO_Port, DI_middle_Pin, GPIO_PIN_SET);
			HAL_GPIO_WritePin(TOP_RIGHT_GPIO_Port ,TOP_RIGHT_Pin, GPIO_PIN_SET);
			HAL_GPIO_WritePin(TOP_MIDDLE_GPIO_Port, TOP_MIDDLE_Pin, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(TOP_LEFT_GPIO_Port, TOP_LEFT_Pin, GPIO_PIN_SET);
			break;
		case 6:
			HAL_GPIO_WritePin(BOTTOM_RIGHT_GPIO_Port, BOTTOM_RIGHT_Pin, GPIO_PIN_SET);
			HAL_GPIO_WritePin(BOTTOM_MIDDLE_GPIO_Port, BOTTOM_MIDDLE_Pin, GPIO_PIN_SET);
			HAL_GPIO_WritePin(BOTTOM_LEFT_GPIO_Port, BOTTOM_LEFT_Pin, GPIO_PIN_SET);
			HAL_GPIO_WritePin(DI_middle_GPIO_Port, DI_middle_Pin, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(TOP_RIGHT_GPIO_Port ,TOP_RIGHT_Pin, GPIO_PIN_SET);
			HAL_GPIO_WritePin(TOP_MIDDLE_GPIO_Port, TOP_MIDDLE_Pin, GPIO_PIN_SET);
			HAL_GPIO_WritePin(TOP_LEFT_GPIO_Port, TOP_LEFT_Pin, GPIO_PIN_SET);
			break;
		default:
			HAL_GPIO_WritePin(BOTTOM_RIGHT_GPIO_Port, BOTTOM_RIGHT_Pin, GPIO_PIN_SET);
			HAL_GPIO_WritePin(BOTTOM_MIDDLE_GPIO_Port, BOTTOM_MIDDLE_Pin, GPIO_PIN_SET);
			HAL_GPIO_WritePin(BOTTOM_LEFT_GPIO_Port, BOTTOM_LEFT_Pin, GPIO_PIN_SET);
			HAL_GPIO_WritePin(DI_middle_GPIO_Port, DI_middle_Pin, GPIO_PIN_SET);
			HAL_GPIO_WritePin(TOP_RIGHT_GPIO_Port ,TOP_RIGHT_Pin, GPIO_PIN_SET);
			HAL_GPIO_WritePin(TOP_MIDDLE_GPIO_Port, TOP_MIDDLE_Pin, GPIO_PIN_SET);
			HAL_GPIO_WritePin(TOP_LEFT_GPIO_Port, TOP_LEFT_Pin, GPIO_PIN_SET);

	}
}

